![](https://backend.seek.onlinedegree.iitm.ac.in/22t1_cs2007/assets/img/com1.png)

![](https://backend.seek.onlinedegree.iitm.ac.in/22t1_cs2007/assets/img/W3G8.JPG)

In [26]:
def create_nonlin_training_set (func, sample_size, std):
    x = np. linspace (0, 1, sample_size) 
    y = func(x) + np.random.normal (scale = std, size=x.shape) 
    return x, y 
def nonlin(x): 
    return np.sin (2* np. pi * x)

print(create_nonlin_training_set (nonlin, 50, std=0.05))

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]), array([-0.02155501,  0.18331135,  0.28539484,  0.39712449,  0.52798198,
        0.52554369,  0.64772389,  0.81892689,  0.92708645,  0.9497985 ,
        0.97637596,  1.00402214,  1.00908639,  0.96902095,  0.95322638,
        0.83169132,  0.8723968 ,  0.78165503,  0.75400533,  0.71675424,
        0.4367544 ,  0.29466465,  0.240

![](https://backend.seek.onlinedegree.iitm.ac.in/22t1_cs2007/assets/img/MQ7.png?seed%3D73849%26url%3Dassets%2Fimg%2FMQ7.png)

In [6]:
import numpy as np 
a= np.arange(1,5).reshape(-1,2) 
b= np.arange (5,9). reshape (2,-1)
print(a)
print(b)
print (a.mean (axis= 0)+b. mean (axis = 1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 7.5 10.5]


In [1]:
import numpy as np

In [5]:
a=np.array([[1,2],[1,2]])
b=np.zeros(a.shape)
print(a,b)


[[1 2]
 [1 2]] [[0. 0.]
 [0. 0.]]


In [6]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
colsum=np.sum(a,axis=0)  #axis=0 means down the column and axis=1 means across a row ->
mean=colsum/a.shape[0]
print(mean)

[1. 2. 3.]


In [10]:
x=a
x.shape
w=np.array([[1],[2],[3]])
w.shape
b=np.array([[4],[5],[6]])
if x.shape[1]==w.shape[0]:
    print(x@w+b)
else:
    print("incompatible")


[[18]
 [19]
 [20]]


In [11]:
w1=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(x*w1)

[[1 4 9]
 [1 4 9]
 [1 4 9]]


In [21]:
u=np.array([[1,2],[3,4]])
v=np.array([[1,2],[3,4]])
print(np.dot(u,v))  #matrix multiplication
print(u@v)   #matrix multiplication
print(u*v)    #hadamard product
print(np.multiply(u,v))   #hadamard product


[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]


In [31]:
import openCV

ModuleNotFoundError: No module named 'openCV'